version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout
      - restore_cache:
          key: fuzzolic-core-{{ checksum ".git/HEAD" }}
      - run: 
          name: Fetching submodules
          command: |
            [[ -f tracer/.git ]] || (git submodule sync && git submodule update --init)
      - save_cache:
          key: fuzzolic-core-{{ checksum ".git/HEAD" }}
          paths:
            - /home/ubuntu/project
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
      - run: 
          name: Building tracer
          working_directory: tracer
          command: |
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || make -j 12
      - save_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
          paths:
            - tracer
      - restore_cache:
          key: fuzzolic-fuzzy-v1
      - run: 
          name: Fetching fuzzy-sat
          working_directory: solver
          command: |
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              cp -a /repo/solver/fuzzy-sat fuzzy-sat
            fi
            [[ -d fuzzy-sat ]] || (git clone git@github.com:season-lab/fuzzy-sat.git && cd fuzzy-sat && git submodule sync && git submodule update --init)
      - save_cache:
          key: fuzzolic-fuzzy-v1
          paths:
            - solver/fuzzy-sat
      - restore_cache:
          key: fuzzolic-z3-{{ checksum "solver/fuzzy-sat/.git/modules/fuzzolic-z3/HEAD" }}
      - run: 
          name: Building Z3
          working_directory: solver/fuzzy-sat
          command: |
            [[ -d fuzzolic-z3/build/dist ]] || (cd fuzzolic-z3 && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/dist && make -j 12 && make install && cd ../..)
            # caching Z3 build when localbuild
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              if [[ -d fuzzolic-z3/build/dist ]]; then
                mkdir -p /repo/solver/fuzzy-sat/fuzzolic-z3/build/
                cp -a fuzzolic-z3/build/dist /repo/solver/fuzzy-sat/fuzzolic-z3/build/
              fi
            fi
      - save_cache:
          key: fuzzolic-z3-{{ checksum "solver/fuzzy-sat/.git/modules/fuzzolic-z3/HEAD" }}
          paths:
            - solver/fuzzy-sat/fuzzolic-z3
      - run:
          name: Setup Environment Variables Z3
          command: |
            echo "export C_INCLUDE_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/include:$C_INCLUDE_PATH" >> $BASH_ENV
            echo "export LIBRARY_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib:$LIBRARY_PATH" >> $BASH_ENV
            echo "export LD_LIBRARY_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib:$LD_LIBRARY_PATH" >> $BASH_ENV
      - restore_cache:
          key: fuzzolic-fuzzy-build-{{ checksum "solver/fuzzy-sat/.git/HEAD" }}
      - run: 
          name: Building fuzzy-sat
          working_directory: solver/fuzzy-sat
          command: |
            [[ -f libZ3Fuzzy.a ]] || make
      - save_cache:
          key: fuzzolic-fuzzy-build-{{ checksum "solver/fuzzy-sat/.git/HEAD" }}
          paths:
            - solver/fuzzy-sat
      - run: 
          name: Building solver frontend
          working_directory: solver
          command: |
            cmake . && make
      - run:
          name: Running tests
          command: |
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              cat /tmp/.bash_env-localbuild-* >> /home/ubuntu/.bashrc
              echo "export AFL_PATH=/AFL" >> /home/ubuntu/.bashrc
            fi
            # git clone git@github.com:season-lab/fuzzy-sat.git
        
