version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: 
          name: building tracer
          command: |
            ls -lh
