version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
      - run: 
          name: building tracer
          working_directory: tracer
          command: |
            ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            make -j 4
      - save_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
          paths:
            - tracer

