version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
      - run: 
          name: building tracer
          working_directory: tracer
          command: |
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || make -j 4
      - save_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
          paths:
            - tracer
      - run: 
          name: building fuzzy-sat
          working_directory: solver
          command: |
            git clone git@github.com:season-lab/fuzzy-sat.git
            cd fuzzy-sat && git submodule sync && git submodule update --init
            ls

