version: 2
jobs:
  build:
    docker:
      - image: ercoppa/fuzzolic-ci-runner
    steps:
      - checkout
      - restore_cache:
          key: fuzzolic-main-{{ checksum ".git/HEAD" }}
      - run: 
          name: fetching submodules
          command: |
            [[ -f tracer/.git ]] || (git submodule sync && git submodule update --init)
            ls -al tracer
            [[ -f tracer/.git ]] || echo "ciao"
            [[ -f tracer/.git ]] && echo "ciao"
      - save_cache:
          key: fuzzolic-main-{{ checksum ".git/HEAD" }}
          paths:
            - ./
      - restore_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
      - run: 
          name: building tracer
          working_directory: tracer
          command: |
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || ./configure --prefix=`pwd`/../build --target-list=x86_64-linux-user
            [[ -f x86_64-linux-user/qemu-x86_64 ]] || make -j 4
      - save_cache:
          key: fuzzolic-tracer-{{ checksum ".git/modules/tracer/HEAD" }}
          paths:
            - tracer
      - restore_cache:
          key: fuzzolic-fuzzy-v1
      - run: 
          name: fetching fuzzy-sat
          working_directory: solver
          command: |
            [[ -d fuzzy-sat ]] || (git clone git@github.com:season-lab/fuzzy-sat.git && cd fuzzy-sat && git submodule sync && git submodule update --init)
      - save_cache:
          key: fuzzolic-fuzzy-v1
          paths:
            - solver/fuzzy-sat
      - restore_cache:
          key: fuzzolic-z3-{{ checksum "solver/fuzzy-sat/.git/modules/fuzzolic-z3/HEAD" }}
      - run: 
          name: building Z3
          working_directory: solver/fuzzy-sat
          command: |
            [[ -d fuzzolic-z3/build/dist ]] || (cd fuzzolic-z3 && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/dist && make -j 4 && make install && cd ../..)
            ls fuzzolic-z3/build/dist
      - save_cache:
          key: fuzzolic-z3-{{ checksum "solver/fuzzy-sat/.git/modules/fuzzolic-z3/HEAD" }}
          paths:
            - solver/fuzzy-sat/fuzzolic-z3
      - run:
          name: Setup Environment Variables Z3
          command: |
            echo "export C_INCLUDE_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/include:$C_INCLUDE_PATH" >> $BASH_ENV
            echo "export LIBRARY_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib:$LIBRARY_PATH" >> $BASH_ENV
            echo "export LD_LIBRARY_PATH=/home/ubuntu/project/solver/fuzzy-sat/fuzzolic-z3/build/dist/lib:$LD_LIBRARY_PATH" >> $BASH_ENV
      - restore_cache:
          key: fuzzolic-fuzzy-build-{{ checksum "solver/fuzzy-sat/.git/HEAD" }}
      - run: 
          name: building fuzzy-sat
          working_directory: solver/fuzzy-sat
          command: |
            make
      - save_cache:
          key: fuzzolic-fuzzy-build-{{ checksum "solver/fuzzy-sat/.git/HEAD" }}
          paths:
            - solver/fuzzy-sat
      - run: 
          name: test
          command: |
            [[ -f tracer/.git ]] || echo "ciao"
            [[ -f tracer/.git ]] && echo "ciao"
